import Head from "next/head";

export default function Cabecalho(){
    return(
        <Head>
            <title>Verão TV Gazeta Sul</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}
